export const WAITLIST_LAUNCH_CONFIRM_PHRASE = "SEND ANNOUNCEMENT";

/** @deprecated Use WAITLIST_LAUNCH_CONFIRM_PHRASE */
export const WAITLIST_LAUNCH_CONFIRM_PHRASE_LEGACY = "SEND LAUNCH EMAILS";

export const WAITLIST_LAUNCH_BATCH_SIZE = 5;
