-- Add new IntakeStatus values (must run before using them in data migration)
ALTER TYPE "IntakeStatus" ADD VALUE IF NOT EXISTS 'CARE_GUIDE_ASSIGNED';
ALTER TYPE "IntakeStatus" ADD VALUE IF NOT EXISTS 'CARE_PLAN';
ALTER TYPE "IntakeStatus" ADD VALUE IF NOT EXISTS 'PROVIDER_RESPONSE';
ALTER TYPE "IntakeStatus" ADD VALUE IF NOT EXISTS 'FOLLOW_UP_7';
ALTER TYPE "IntakeStatus" ADD VALUE IF NOT EXISTS 'FOLLOW_UP_30';
ALTER TYPE "IntakeStatus" ADD VALUE IF NOT EXISTS 'FOLLOW_UP_90';
